services:
  spring-backend:
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_PASSWORD: password
      DB_HOSTNAME: mysql2
    depends_on:
      - mysql2
  mysql2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    